FORMAT: 1A
HOST: http://195.201.116.176:8000/

# ETOMIC FAUCET

ETOMIC faucet is simple NodeJS backend sending up to 100 ETOMIC to address.
As only 1 ETOMIC is required for any amount of ETH/ERC20 trade 100 ETOMIC will be more than enough.

## Get ETOMIC [/getEtomic]

### Get ETOMIC [POST]

+ Response 200 (application/json)

+ Request (application/json)

        {
            "etomicAddress": "RETqFbShvJvP4s2pgjBxAKGz7ftWN1cZFz"
        }

+ Response 200 (application/json)

    + Body

            {
                "txIds": [
                    "3636a320ec94b0a4c33655877c8642df69487beac910fb64809c6edd0392a6a3",
                    "6a8110e2b8b6565203349ffaeb8fc73022c3a24df4fa67f94a2e2117e0506749",
                    "79150df6beff26e8daf2d4a31e7bfb0e1d8d8cbe25c760775f0f7558777842ae"
                ]
            }
